name: BattlegroundStore
main: com.division.battlegrounds.store.core.BattlegroundsStore
version: 0.0.1D
description: Implementation of the Battlegrounds API's token system.
authors: [Mastershake71]
depend: [Battlegrounds]